name: flutter_mcp_server
description: "A Flutter app showing how to expose functions to agents via MCP."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.6.0
  provider: ^6.1.5+1
  path_provider: ^2.1.5
  path: ^1.9.1
  posix: ^6.0.3
  dart_ipc: ^1.0.1
  json_schema_builder: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
